// Code generated by Wire protocol buffer compiler, do not edit.
// Source: SignUpService in 17111111.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.electrolytej.network.api

import com.electrolytej.network.model.SignUpReq
import com.electrolytej.network.model.SignUpResp
import com.squareup.wire.GrpcCall
import com.squareup.wire.GrpcClient
import com.squareup.wire.GrpcMethod
import kotlin.Suppress

public class GrpcSignUpServiceClient(
  private val client: GrpcClient,
) : SignUpServiceClient {
  override fun signup(): GrpcCall<SignUpReq, SignUpResp> = client.newCall(GrpcMethod(
      path = "/SignUpService/signup",
      requestAdapter = SignUpReq.ADAPTER,
      responseAdapter = SignUpResp.ADAPTER
  ))
}
