// Code generated by Wire protocol buffer compiler, do not edit.
// Source: SignInService in 17111111.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.electrolytej.network.api

import com.electrolytej.network.model.SignInReq
import com.electrolytej.network.model.SignInResp
import com.squareup.wire.GrpcCall
import com.squareup.wire.GrpcClient
import com.squareup.wire.GrpcMethod
import kotlin.Suppress

public class GrpcSignInServiceClient(
  private val client: GrpcClient,
) : SignInServiceClient {
  override fun signin(): GrpcCall<SignInReq, SignInResp> = client.newCall(GrpcMethod(
      path = "/SignInService/signin",
      requestAdapter = SignInReq.ADAPTER,
      responseAdapter = SignInResp.ADAPTER
  ))
}
