// Code generated by Wire protocol buffer compiler, do not edit.
// Source: SignUpService in 17111111.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.electrolytej.network.api

import com.electrolytej.network.model.SignUpReq
import com.electrolytej.network.model.SignUpResp
import com.squareup.wire.GrpcCall
import com.squareup.wire.Service
import kotlin.Suppress

public interface SignUpServiceClient : Service {
  public fun signup(): GrpcCall<SignUpReq, SignUpResp>
}
