// Code generated by Wire protocol buffer compiler, do not edit.
// Source: SignInService in 17111111.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.electrolytej.network.api

import com.electrolytej.network.model.SignInReq
import com.electrolytej.network.model.SignInResp
import com.squareup.wire.GrpcCall
import com.squareup.wire.Service
import kotlin.Suppress

public interface SignInServiceClient : Service {
  public fun signin(): GrpcCall<SignInReq, SignInResp>
}
