// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.electrolytej.network.model.SignInService in 17121212.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.electrolytej.network.model

import com.squareup.wire.GrpcCall
import com.squareup.wire.GrpcClient
import com.squareup.wire.GrpcMethod
import kotlin.Suppress

public class GrpcSignInServiceClient(
  private val client: GrpcClient,
) : SignInServiceClient {
  override fun signin(): GrpcCall<SignInReq, SignInResp> = client.newCall(GrpcMethod(
      path = "/com.electrolytej.network.model.SignInService/signin",
      requestAdapter = SignInReq.ADAPTER,
      responseAdapter = SignInResp.ADAPTER
  ))
}
