// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.electrolytej.network.model.SignUpService in 17111111.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.electrolytej.network.model

import com.squareup.wire.GrpcCall
import com.squareup.wire.GrpcClient
import com.squareup.wire.GrpcMethod
import kotlin.Suppress

public class GrpcSignUpServiceClient(
  private val client: GrpcClient,
) : SignUpServiceClient {
  override fun signup(): GrpcCall<SignUpReq, SignUpResp> = client.newCall(GrpcMethod(
      path = "/com.electrolytej.network.model.SignUpService/signup",
      requestAdapter = SignUpReq.ADAPTER,
      responseAdapter = SignUpResp.ADAPTER
  ))
}
