// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.electrolytej.network.model.SignUpReq in 17111111.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.electrolytej.network.model

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class SignUpReq(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val id: Int = 0,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val password: String = "",
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val verificationCode: Int = 0,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<SignUpReq, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is SignUpReq) return false
    if (unknownFields != other.unknownFields) return false
    if (id != other.id) return false
    if (password != other.password) return false
    if (verificationCode != other.verificationCode) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + id.hashCode()
      result = result * 37 + password.hashCode()
      result = result * 37 + verificationCode.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """id=$id"""
    result += """password=${sanitize(password)}"""
    result += """verificationCode=$verificationCode"""
    return result.joinToString(prefix = "SignUpReq{", separator = ", ", postfix = "}")
  }

  public fun copy(
    id: Int = this.id,
    password: String = this.password,
    verificationCode: Int = this.verificationCode,
    unknownFields: ByteString = this.unknownFields,
  ): SignUpReq = SignUpReq(id, password, verificationCode, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<SignUpReq> = object : ProtoAdapter<SignUpReq>(
      FieldEncoding.LENGTH_DELIMITED, 
      SignUpReq::class, 
      "type.googleapis.com/com.electrolytej.network.model.SignUpReq", 
      PROTO_3, 
      null, 
      "17111111.proto"
    ) {
      override fun encodedSize(`value`: SignUpReq): Int {
        var size = value.unknownFields.size
        if (value.id != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(1, value.id)
        }
        if (value.password != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.password)
        }
        if (value.verificationCode != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(3, value.verificationCode)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: SignUpReq) {
        if (value.id != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 1, value.id)
        }
        if (value.password != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.password)
        }
        if (value.verificationCode != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.verificationCode)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: SignUpReq) {
        writer.writeBytes(value.unknownFields)
        if (value.verificationCode != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.verificationCode)
        }
        if (value.password != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.password)
        }
        if (value.id != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 1, value.id)
        }
      }

      override fun decode(reader: ProtoReader): SignUpReq {
        var id: Int = 0
        var password: String = ""
        var verificationCode: Int = 0
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> id = ProtoAdapter.INT32.decode(reader)
            2 -> password = ProtoAdapter.STRING.decode(reader)
            3 -> verificationCode = ProtoAdapter.INT32.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return SignUpReq(
          id = id,
          password = password,
          verificationCode = verificationCode,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: SignUpReq): SignUpReq = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
