// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.electrolytej.network.model.SignInService in 17121212.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.electrolytej.network.model

import com.squareup.wire.GrpcCall
import com.squareup.wire.Service
import kotlin.Suppress

public interface SignInServiceClient : Service {
  public fun signin(): GrpcCall<SignInReq, SignInResp>
}
