// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.electrolytej.network.model.TokenState in TokenState.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.electrolytej.network.model

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int
import kotlin.Suppress

public enum class TokenState(
  override val `value`: Int,
) : WireEnum {
  NONE(0),
  UNAUTHORIZED(1),
  OTHERS(2),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<TokenState> = object : EnumAdapter<TokenState>(
      TokenState::class, 
      PROTO_3, 
      TokenState.NONE
    ) {
      override fun fromValue(`value`: Int): TokenState? = TokenState.fromValue(`value`)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): TokenState? = when (`value`) {
      0 -> NONE
      1 -> UNAUTHORIZED
      2 -> OTHERS
      else -> null
    }
  }
}
