// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Profile1.proto

package com.electrolytej.network.model;

public final class Profile1 {
  private Profile1() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.electrolytej.network.model.Msg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string foo = 1;</code>
     * @return The foo.
     */
    java.lang.String getFoo();
    /**
     * <code>string foo = 1;</code>
     * @return The bytes for foo.
     */
    com.google.protobuf.ByteString
        getFooBytes();

    /**
     * <code>.com.electrolytej.network.model.SecondMsg blah = 2;</code>
     * @return Whether the blah field is set.
     */
    boolean hasBlah();
    /**
     * <code>.com.electrolytej.network.model.SecondMsg blah = 2;</code>
     * @return The blah.
     */
    com.electrolytej.network.model.Profile1.SecondMsg getBlah();
    /**
     * <code>.com.electrolytej.network.model.SecondMsg blah = 2;</code>
     */
    com.electrolytej.network.model.Profile1.SecondMsgOrBuilder getBlahOrBuilder();
  }
  /**
   * Protobuf type {@code com.electrolytej.network.model.Msg}
   */
  public static final class Msg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.electrolytej.network.model.Msg)
      MsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Msg.newBuilder() to construct.
    private Msg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Msg() {
      foo_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Msg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.electrolytej.network.model.Profile1.internal_static_com_electrolytej_network_model_Msg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.electrolytej.network.model.Profile1.internal_static_com_electrolytej_network_model_Msg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.electrolytej.network.model.Profile1.Msg.class, com.electrolytej.network.model.Profile1.Msg.Builder.class);
    }

    public static final int FOO_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object foo_ = "";
    /**
     * <code>string foo = 1;</code>
     * @return The foo.
     */
    @java.lang.Override
    public java.lang.String getFoo() {
      java.lang.Object ref = foo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        foo_ = s;
        return s;
      }
    }
    /**
     * <code>string foo = 1;</code>
     * @return The bytes for foo.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFooBytes() {
      java.lang.Object ref = foo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        foo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BLAH_FIELD_NUMBER = 2;
    private com.electrolytej.network.model.Profile1.SecondMsg blah_;
    /**
     * <code>.com.electrolytej.network.model.SecondMsg blah = 2;</code>
     * @return Whether the blah field is set.
     */
    @java.lang.Override
    public boolean hasBlah() {
      return blah_ != null;
    }
    /**
     * <code>.com.electrolytej.network.model.SecondMsg blah = 2;</code>
     * @return The blah.
     */
    @java.lang.Override
    public com.electrolytej.network.model.Profile1.SecondMsg getBlah() {
      return blah_ == null ? com.electrolytej.network.model.Profile1.SecondMsg.getDefaultInstance() : blah_;
    }
    /**
     * <code>.com.electrolytej.network.model.SecondMsg blah = 2;</code>
     */
    @java.lang.Override
    public com.electrolytej.network.model.Profile1.SecondMsgOrBuilder getBlahOrBuilder() {
      return blah_ == null ? com.electrolytej.network.model.Profile1.SecondMsg.getDefaultInstance() : blah_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(foo_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, foo_);
      }
      if (blah_ != null) {
        output.writeMessage(2, getBlah());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(foo_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, foo_);
      }
      if (blah_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getBlah());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.electrolytej.network.model.Profile1.Msg)) {
        return super.equals(obj);
      }
      com.electrolytej.network.model.Profile1.Msg other = (com.electrolytej.network.model.Profile1.Msg) obj;

      if (!getFoo()
          .equals(other.getFoo())) return false;
      if (hasBlah() != other.hasBlah()) return false;
      if (hasBlah()) {
        if (!getBlah()
            .equals(other.getBlah())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FOO_FIELD_NUMBER;
      hash = (53 * hash) + getFoo().hashCode();
      if (hasBlah()) {
        hash = (37 * hash) + BLAH_FIELD_NUMBER;
        hash = (53 * hash) + getBlah().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.electrolytej.network.model.Profile1.Msg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.electrolytej.network.model.Profile1.Msg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.electrolytej.network.model.Profile1.Msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.electrolytej.network.model.Profile1.Msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.electrolytej.network.model.Profile1.Msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.electrolytej.network.model.Profile1.Msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.electrolytej.network.model.Profile1.Msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.electrolytej.network.model.Profile1.Msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.electrolytej.network.model.Profile1.Msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.electrolytej.network.model.Profile1.Msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.electrolytej.network.model.Profile1.Msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.electrolytej.network.model.Profile1.Msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.electrolytej.network.model.Profile1.Msg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.electrolytej.network.model.Msg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.electrolytej.network.model.Msg)
        com.electrolytej.network.model.Profile1.MsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.electrolytej.network.model.Profile1.internal_static_com_electrolytej_network_model_Msg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.electrolytej.network.model.Profile1.internal_static_com_electrolytej_network_model_Msg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.electrolytej.network.model.Profile1.Msg.class, com.electrolytej.network.model.Profile1.Msg.Builder.class);
      }

      // Construct using com.electrolytej.network.model.Profile1.Msg.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        foo_ = "";
        blah_ = null;
        if (blahBuilder_ != null) {
          blahBuilder_.dispose();
          blahBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.electrolytej.network.model.Profile1.internal_static_com_electrolytej_network_model_Msg_descriptor;
      }

      @java.lang.Override
      public com.electrolytej.network.model.Profile1.Msg getDefaultInstanceForType() {
        return com.electrolytej.network.model.Profile1.Msg.getDefaultInstance();
      }

      @java.lang.Override
      public com.electrolytej.network.model.Profile1.Msg build() {
        com.electrolytej.network.model.Profile1.Msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.electrolytej.network.model.Profile1.Msg buildPartial() {
        com.electrolytej.network.model.Profile1.Msg result = new com.electrolytej.network.model.Profile1.Msg(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.electrolytej.network.model.Profile1.Msg result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.foo_ = foo_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.blah_ = blahBuilder_ == null
              ? blah_
              : blahBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.electrolytej.network.model.Profile1.Msg) {
          return mergeFrom((com.electrolytej.network.model.Profile1.Msg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.electrolytej.network.model.Profile1.Msg other) {
        if (other == com.electrolytej.network.model.Profile1.Msg.getDefaultInstance()) return this;
        if (!other.getFoo().isEmpty()) {
          foo_ = other.foo_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasBlah()) {
          mergeBlah(other.getBlah());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                foo_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getBlahFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object foo_ = "";
      /**
       * <code>string foo = 1;</code>
       * @return The foo.
       */
      public java.lang.String getFoo() {
        java.lang.Object ref = foo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          foo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string foo = 1;</code>
       * @return The bytes for foo.
       */
      public com.google.protobuf.ByteString
          getFooBytes() {
        java.lang.Object ref = foo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          foo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string foo = 1;</code>
       * @param value The foo to set.
       * @return This builder for chaining.
       */
      public Builder setFoo(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        foo_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string foo = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFoo() {
        foo_ = getDefaultInstance().getFoo();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string foo = 1;</code>
       * @param value The bytes for foo to set.
       * @return This builder for chaining.
       */
      public Builder setFooBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        foo_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.electrolytej.network.model.Profile1.SecondMsg blah_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.electrolytej.network.model.Profile1.SecondMsg, com.electrolytej.network.model.Profile1.SecondMsg.Builder, com.electrolytej.network.model.Profile1.SecondMsgOrBuilder> blahBuilder_;
      /**
       * <code>.com.electrolytej.network.model.SecondMsg blah = 2;</code>
       * @return Whether the blah field is set.
       */
      public boolean hasBlah() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.com.electrolytej.network.model.SecondMsg blah = 2;</code>
       * @return The blah.
       */
      public com.electrolytej.network.model.Profile1.SecondMsg getBlah() {
        if (blahBuilder_ == null) {
          return blah_ == null ? com.electrolytej.network.model.Profile1.SecondMsg.getDefaultInstance() : blah_;
        } else {
          return blahBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.electrolytej.network.model.SecondMsg blah = 2;</code>
       */
      public Builder setBlah(com.electrolytej.network.model.Profile1.SecondMsg value) {
        if (blahBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          blah_ = value;
        } else {
          blahBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.com.electrolytej.network.model.SecondMsg blah = 2;</code>
       */
      public Builder setBlah(
          com.electrolytej.network.model.Profile1.SecondMsg.Builder builderForValue) {
        if (blahBuilder_ == null) {
          blah_ = builderForValue.build();
        } else {
          blahBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.com.electrolytej.network.model.SecondMsg blah = 2;</code>
       */
      public Builder mergeBlah(com.electrolytej.network.model.Profile1.SecondMsg value) {
        if (blahBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            blah_ != null &&
            blah_ != com.electrolytej.network.model.Profile1.SecondMsg.getDefaultInstance()) {
            getBlahBuilder().mergeFrom(value);
          } else {
            blah_ = value;
          }
        } else {
          blahBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.com.electrolytej.network.model.SecondMsg blah = 2;</code>
       */
      public Builder clearBlah() {
        bitField0_ = (bitField0_ & ~0x00000002);
        blah_ = null;
        if (blahBuilder_ != null) {
          blahBuilder_.dispose();
          blahBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.com.electrolytej.network.model.SecondMsg blah = 2;</code>
       */
      public com.electrolytej.network.model.Profile1.SecondMsg.Builder getBlahBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getBlahFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.electrolytej.network.model.SecondMsg blah = 2;</code>
       */
      public com.electrolytej.network.model.Profile1.SecondMsgOrBuilder getBlahOrBuilder() {
        if (blahBuilder_ != null) {
          return blahBuilder_.getMessageOrBuilder();
        } else {
          return blah_ == null ?
              com.electrolytej.network.model.Profile1.SecondMsg.getDefaultInstance() : blah_;
        }
      }
      /**
       * <code>.com.electrolytej.network.model.SecondMsg blah = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.electrolytej.network.model.Profile1.SecondMsg, com.electrolytej.network.model.Profile1.SecondMsg.Builder, com.electrolytej.network.model.Profile1.SecondMsgOrBuilder> 
          getBlahFieldBuilder() {
        if (blahBuilder_ == null) {
          blahBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.electrolytej.network.model.Profile1.SecondMsg, com.electrolytej.network.model.Profile1.SecondMsg.Builder, com.electrolytej.network.model.Profile1.SecondMsgOrBuilder>(
                  getBlah(),
                  getParentForChildren(),
                  isClean());
          blah_ = null;
        }
        return blahBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.electrolytej.network.model.Msg)
    }

    // @@protoc_insertion_point(class_scope:com.electrolytej.network.model.Msg)
    private static final com.electrolytej.network.model.Profile1.Msg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.electrolytej.network.model.Profile1.Msg();
    }

    public static com.electrolytej.network.model.Profile1.Msg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Msg>
        PARSER = new com.google.protobuf.AbstractParser<Msg>() {
      @java.lang.Override
      public Msg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Msg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Msg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.electrolytej.network.model.Profile1.Msg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SecondMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.electrolytej.network.model.SecondMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 blah = 1;</code>
     * @return The blah.
     */
    int getBlah();
  }
  /**
   * Protobuf type {@code com.electrolytej.network.model.SecondMsg}
   */
  public static final class SecondMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.electrolytej.network.model.SecondMsg)
      SecondMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SecondMsg.newBuilder() to construct.
    private SecondMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SecondMsg() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SecondMsg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.electrolytej.network.model.Profile1.internal_static_com_electrolytej_network_model_SecondMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.electrolytej.network.model.Profile1.internal_static_com_electrolytej_network_model_SecondMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.electrolytej.network.model.Profile1.SecondMsg.class, com.electrolytej.network.model.Profile1.SecondMsg.Builder.class);
    }

    public static final int BLAH_FIELD_NUMBER = 1;
    private int blah_ = 0;
    /**
     * <code>int32 blah = 1;</code>
     * @return The blah.
     */
    @java.lang.Override
    public int getBlah() {
      return blah_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (blah_ != 0) {
        output.writeInt32(1, blah_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (blah_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, blah_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.electrolytej.network.model.Profile1.SecondMsg)) {
        return super.equals(obj);
      }
      com.electrolytej.network.model.Profile1.SecondMsg other = (com.electrolytej.network.model.Profile1.SecondMsg) obj;

      if (getBlah()
          != other.getBlah()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BLAH_FIELD_NUMBER;
      hash = (53 * hash) + getBlah();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.electrolytej.network.model.Profile1.SecondMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.electrolytej.network.model.Profile1.SecondMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.electrolytej.network.model.Profile1.SecondMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.electrolytej.network.model.Profile1.SecondMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.electrolytej.network.model.Profile1.SecondMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.electrolytej.network.model.Profile1.SecondMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.electrolytej.network.model.Profile1.SecondMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.electrolytej.network.model.Profile1.SecondMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.electrolytej.network.model.Profile1.SecondMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.electrolytej.network.model.Profile1.SecondMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.electrolytej.network.model.Profile1.SecondMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.electrolytej.network.model.Profile1.SecondMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.electrolytej.network.model.Profile1.SecondMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.electrolytej.network.model.SecondMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.electrolytej.network.model.SecondMsg)
        com.electrolytej.network.model.Profile1.SecondMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.electrolytej.network.model.Profile1.internal_static_com_electrolytej_network_model_SecondMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.electrolytej.network.model.Profile1.internal_static_com_electrolytej_network_model_SecondMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.electrolytej.network.model.Profile1.SecondMsg.class, com.electrolytej.network.model.Profile1.SecondMsg.Builder.class);
      }

      // Construct using com.electrolytej.network.model.Profile1.SecondMsg.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        blah_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.electrolytej.network.model.Profile1.internal_static_com_electrolytej_network_model_SecondMsg_descriptor;
      }

      @java.lang.Override
      public com.electrolytej.network.model.Profile1.SecondMsg getDefaultInstanceForType() {
        return com.electrolytej.network.model.Profile1.SecondMsg.getDefaultInstance();
      }

      @java.lang.Override
      public com.electrolytej.network.model.Profile1.SecondMsg build() {
        com.electrolytej.network.model.Profile1.SecondMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.electrolytej.network.model.Profile1.SecondMsg buildPartial() {
        com.electrolytej.network.model.Profile1.SecondMsg result = new com.electrolytej.network.model.Profile1.SecondMsg(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.electrolytej.network.model.Profile1.SecondMsg result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.blah_ = blah_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.electrolytej.network.model.Profile1.SecondMsg) {
          return mergeFrom((com.electrolytej.network.model.Profile1.SecondMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.electrolytej.network.model.Profile1.SecondMsg other) {
        if (other == com.electrolytej.network.model.Profile1.SecondMsg.getDefaultInstance()) return this;
        if (other.getBlah() != 0) {
          setBlah(other.getBlah());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                blah_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int blah_ ;
      /**
       * <code>int32 blah = 1;</code>
       * @return The blah.
       */
      @java.lang.Override
      public int getBlah() {
        return blah_;
      }
      /**
       * <code>int32 blah = 1;</code>
       * @param value The blah to set.
       * @return This builder for chaining.
       */
      public Builder setBlah(int value) {
        
        blah_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 blah = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBlah() {
        bitField0_ = (bitField0_ & ~0x00000001);
        blah_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.electrolytej.network.model.SecondMsg)
    }

    // @@protoc_insertion_point(class_scope:com.electrolytej.network.model.SecondMsg)
    private static final com.electrolytej.network.model.Profile1.SecondMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.electrolytej.network.model.Profile1.SecondMsg();
    }

    public static com.electrolytej.network.model.Profile1.SecondMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SecondMsg>
        PARSER = new com.google.protobuf.AbstractParser<SecondMsg>() {
      @java.lang.Override
      public SecondMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SecondMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SecondMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.electrolytej.network.model.Profile1.SecondMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_electrolytej_network_model_Msg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_electrolytej_network_model_Msg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_electrolytej_network_model_SecondMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_electrolytej_network_model_SecondMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Profile1.proto\022\036com.electrolytej.netwo" +
      "rk.model\"K\n\003Msg\022\013\n\003foo\030\001 \001(\t\0227\n\004blah\030\002 \001" +
      "(\0132).com.electrolytej.network.model.Seco" +
      "ndMsg\"\031\n\tSecondMsg\022\014\n\004blah\030\001 \001(\005B*\n\036com." +
      "electrolytej.network.modelB\010Profile1b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_electrolytej_network_model_Msg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_electrolytej_network_model_Msg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_electrolytej_network_model_Msg_descriptor,
        new java.lang.String[] { "Foo", "Blah", });
    internal_static_com_electrolytej_network_model_SecondMsg_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_electrolytej_network_model_SecondMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_electrolytej_network_model_SecondMsg_descriptor,
        new java.lang.String[] { "Blah", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
