// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 17121212.proto

package com.electrolytej.network.model;

public interface SignInRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.electrolytej.network.model.SignInResp)
    com.google.protobuf.MessageOrBuilder {
}
