// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 17121212.proto

package com.electrolytej.network.model;

public final class SignInProto {
  private SignInProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_electrolytej_network_model_SignInReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_electrolytej_network_model_SignInReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_electrolytej_network_model_SignInResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_electrolytej_network_model_SignInResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\01617121212.proto\022\036com.electrolytej.netwo" +
      "rk.model\"\013\n\tSignInReq\"\014\n\nSignInResp2p\n\rS" +
      "ignInService\022_\n\006signin\022).com.electrolyte" +
      "j.network.model.SignInReq\032*.com.electrol" +
      "ytej.network.model.SignInRespB2\n\036com.ele" +
      "ctrolytej.network.modelB\013SignInProtoP\001\210\001" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_electrolytej_network_model_SignInReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_electrolytej_network_model_SignInReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_electrolytej_network_model_SignInReq_descriptor,
        new java.lang.String[] { });
    internal_static_com_electrolytej_network_model_SignInResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_electrolytej_network_model_SignInResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_electrolytej_network_model_SignInResp_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
