// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 17121212.proto

package com.electrolytej.network.model;

public interface SignInReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.electrolytej.network.model.SignInReq)
    com.google.protobuf.MessageOrBuilder {
}
