// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 17111111.proto

package com.electrolytej.network.model;

/**
 * Protobuf service {@code com.electrolytej.network.model.SignUpService}
 */
public  abstract class SignUpService
    implements com.google.protobuf.Service {
  protected SignUpService() {}

  public interface Interface {
    /**
     * <code>rpc signup(.com.electrolytej.network.model.SignUpReq) returns (.com.electrolytej.network.model.SignUpResp);</code>
     */
    public abstract void signup(
        com.google.protobuf.RpcController controller,
        com.electrolytej.network.model.SignUpReq request,
        com.google.protobuf.RpcCallback<com.electrolytej.network.model.SignUpResp> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new SignUpService() {
      @java.lang.Override
      public  void signup(
          com.google.protobuf.RpcController controller,
          com.electrolytej.network.model.SignUpReq request,
          com.google.protobuf.RpcCallback<com.electrolytej.network.model.SignUpResp> done) {
        impl.signup(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.signup(controller, (com.electrolytej.network.model.SignUpReq)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.electrolytej.network.model.SignUpReq.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.electrolytej.network.model.SignUpResp.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <code>rpc signup(.com.electrolytej.network.model.SignUpReq) returns (.com.electrolytej.network.model.SignUpResp);</code>
   */
  public abstract void signup(
      com.google.protobuf.RpcController controller,
      com.electrolytej.network.model.SignUpReq request,
      com.google.protobuf.RpcCallback<com.electrolytej.network.model.SignUpResp> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return com.electrolytej.network.model.SignUpProto.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.signup(controller, (com.electrolytej.network.model.SignUpReq)request,
          com.google.protobuf.RpcUtil.<com.electrolytej.network.model.SignUpResp>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.electrolytej.network.model.SignUpReq.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.electrolytej.network.model.SignUpResp.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends com.electrolytej.network.model.SignUpService implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void signup(
        com.google.protobuf.RpcController controller,
        com.electrolytej.network.model.SignUpReq request,
        com.google.protobuf.RpcCallback<com.electrolytej.network.model.SignUpResp> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.electrolytej.network.model.SignUpResp.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.electrolytej.network.model.SignUpResp.class,
          com.electrolytej.network.model.SignUpResp.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public com.electrolytej.network.model.SignUpResp signup(
        com.google.protobuf.RpcController controller,
        com.electrolytej.network.model.SignUpReq request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public com.electrolytej.network.model.SignUpResp signup(
        com.google.protobuf.RpcController controller,
        com.electrolytej.network.model.SignUpReq request)
        throws com.google.protobuf.ServiceException {
      return (com.electrolytej.network.model.SignUpResp) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.electrolytej.network.model.SignUpResp.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:com.electrolytej.network.model.SignUpService)
}

