// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 17111111.proto

package com.electrolytej.network.model;

public interface SignUpRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.electrolytej.network.model.SignUpResp)
    com.google.protobuf.MessageOrBuilder {
}
