// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 17111111.proto

package com.electrolytej.network.model;

public interface SignUpReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.electrolytej.network.model.SignUpReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string password = 2;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>int32 verificationCode = 3;</code>
   * @return The verificationCode.
   */
  int getVerificationCode();
}
