// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 17121212.proto

package com.electrolytej.network.model;

/**
 * Protobuf service {@code com.electrolytej.network.model.SignInService}
 */
public  abstract class SignInService
    implements com.google.protobuf.Service {
  protected SignInService() {}

  public interface Interface {
    /**
     * <code>rpc signin(.com.electrolytej.network.model.SignInReq) returns (.com.electrolytej.network.model.SignInResp);</code>
     */
    public abstract void signin(
        com.google.protobuf.RpcController controller,
        com.electrolytej.network.model.SignInReq request,
        com.google.protobuf.RpcCallback<com.electrolytej.network.model.SignInResp> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new SignInService() {
      @java.lang.Override
      public  void signin(
          com.google.protobuf.RpcController controller,
          com.electrolytej.network.model.SignInReq request,
          com.google.protobuf.RpcCallback<com.electrolytej.network.model.SignInResp> done) {
        impl.signin(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.signin(controller, (com.electrolytej.network.model.SignInReq)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.electrolytej.network.model.SignInReq.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.electrolytej.network.model.SignInResp.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <code>rpc signin(.com.electrolytej.network.model.SignInReq) returns (.com.electrolytej.network.model.SignInResp);</code>
   */
  public abstract void signin(
      com.google.protobuf.RpcController controller,
      com.electrolytej.network.model.SignInReq request,
      com.google.protobuf.RpcCallback<com.electrolytej.network.model.SignInResp> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return com.electrolytej.network.model.SignInProto.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.signin(controller, (com.electrolytej.network.model.SignInReq)request,
          com.google.protobuf.RpcUtil.<com.electrolytej.network.model.SignInResp>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.electrolytej.network.model.SignInReq.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.electrolytej.network.model.SignInResp.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends com.electrolytej.network.model.SignInService implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void signin(
        com.google.protobuf.RpcController controller,
        com.electrolytej.network.model.SignInReq request,
        com.google.protobuf.RpcCallback<com.electrolytej.network.model.SignInResp> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.electrolytej.network.model.SignInResp.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.electrolytej.network.model.SignInResp.class,
          com.electrolytej.network.model.SignInResp.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public com.electrolytej.network.model.SignInResp signin(
        com.google.protobuf.RpcController controller,
        com.electrolytej.network.model.SignInReq request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public com.electrolytej.network.model.SignInResp signin(
        com.google.protobuf.RpcController controller,
        com.electrolytej.network.model.SignInReq request)
        throws com.google.protobuf.ServiceException {
      return (com.electrolytej.network.model.SignInResp) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.electrolytej.network.model.SignInResp.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:com.electrolytej.network.model.SignInService)
}

