// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 17111111.proto

package com.electrolytej.network.model;

public final class SignUpProto {
  private SignUpProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_electrolytej_network_model_SignUpReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_electrolytej_network_model_SignUpReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_electrolytej_network_model_SignUpResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_electrolytej_network_model_SignUpResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\01617111111.proto\022\036com.electrolytej.netwo" +
      "rk.model\"C\n\tSignUpReq\022\n\n\002id\030\001 \001(\005\022\020\n\010pas" +
      "sword\030\002 \001(\t\022\030\n\020verificationCode\030\003 \001(\005\"\014\n" +
      "\nSignUpResp2p\n\rSignUpService\022_\n\006signup\022)" +
      ".com.electrolytej.network.model.SignUpRe" +
      "q\032*.com.electrolytej.network.model.SignU" +
      "pRespB2\n\036com.electrolytej.network.modelB" +
      "\013SignUpProtoP\001\210\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_electrolytej_network_model_SignUpReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_electrolytej_network_model_SignUpReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_electrolytej_network_model_SignUpReq_descriptor,
        new java.lang.String[] { "Id", "Password", "VerificationCode", });
    internal_static_com_electrolytej_network_model_SignUpResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_electrolytej_network_model_SignUpResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_electrolytej_network_model_SignUpResp_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
