// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TokenState.proto

package com.electrolytej.network.model;

public final class TokenStateOuterClass {
  private TokenStateOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   *option java_outer_classname = "TokenState";
   * </pre>
   *
   * Protobuf enum {@code com.electrolytej.network.model.TokenState}
   */
  public enum TokenState
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NONE = 0;</code>
     */
    NONE(0),
    /**
     * <code>UNAUTHORIZED = 1;</code>
     */
    UNAUTHORIZED(1),
    /**
     * <code>OTHERS = 2;</code>
     */
    OTHERS(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>NONE = 0;</code>
     */
    public static final int NONE_VALUE = 0;
    /**
     * <code>UNAUTHORIZED = 1;</code>
     */
    public static final int UNAUTHORIZED_VALUE = 1;
    /**
     * <code>OTHERS = 2;</code>
     */
    public static final int OTHERS_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TokenState valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static TokenState forNumber(int value) {
      switch (value) {
        case 0: return NONE;
        case 1: return UNAUTHORIZED;
        case 2: return OTHERS;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TokenState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TokenState> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TokenState>() {
            public TokenState findValueByNumber(int number) {
              return TokenState.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.electrolytej.network.model.TokenStateOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final TokenState[] VALUES = values();

    public static TokenState valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TokenState(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.electrolytej.network.model.TokenState)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020TokenState.proto\022\036com.electrolytej.net" +
      "work.model*4\n\nTokenState\022\010\n\004NONE\020\000\022\020\n\014UN" +
      "AUTHORIZED\020\001\022\n\n\006OTHERS\020\002B \n\036com.electrol" +
      "ytej.network.modelb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
