//
// Category.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Category: Codable { 


    /** 分组ID编号 */
    public var id: Int64?
    /** 分组名称 */
    public var name: String?

    public init(id: Int64?, name: String?) {
        self.id = id
        self.name = name
    }

}
