//
// InlineObject.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject: Codable { 


    /** 宠物名 */
    public var name: String
    /** 宠物销售状态 */
    public var status: String

    public init(name: String, status: String) {
        self.name = name
        self.status = status
    }

}
