//
// InlineResponse201.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse201: Codable { 


    public var code: Int
    public var data: Pet

    public init(code: Int, data: Pet) {
        self.code = code
        self.data = data
    }

}
