//
// Pet.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Pet: Codable { 


    public enum Status: String, Codable, CaseIterable {
        case available = "available"
        case pending = "pending"
        case sold = "sold"
    }
    /** 宠物ID编号 */
    public var id: Int64
    public var category: Category
    /** 名称 */
    public var name: String
    /** 照片URL */
    public var photoUrls: [String]
    /** 标签 */
    public var tags: [Tag]
    /** 宠物销售状态 */
    public var status: Status

    public init(id: Int64, category: Category, name: String, photoUrls: [String], tags: [Tag], status: Status) {
        self.id = id
        self.category = category
        self.name = name
        self.photoUrls = photoUrls
        self.tags = tags
        self.status = status
    }

}
