//
// Tag.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Tag: Codable { 


    /** 标签ID编号 */
    public var id: Int64?
    /** 标签名称 */
    public var name: String?

    public init(id: Int64?, name: String?) {
        self.id = id
        self.name = name
    }

}
