/**
 * meetyou
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.electrolytej.main;

import com.electrolytej.main.V1GetadDeepLinkTracking;
import com.electrolytej.main.V1GetadPicMaxSize;
import com.electrolytej.main.V1GetadUser;
import java.math.BigDecimal;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;

@ApiModel(description = "")
public class InlineResponse2003 implements Serializable {
  
  @SerializedName("ad_source_type")
  private Integer adSourceType = null;
  @SerializedName("attr_id")
  private Integer attrId = null;
  @SerializedName("attr_text")
  private String attrText = null;
  @SerializedName("click_ping")
  private List<String> clickPing = null;
  @SerializedName("close_by_reason")
  private Integer closeByReason = null;
  @SerializedName("deep_link_tracking")
  private V1GetadDeepLinkTracking deepLinkTracking = null;
  @SerializedName("encourage_finish_time")
  private Integer encourageFinishTime = null;
  @SerializedName("encourage_video_time")
  private Integer encourageVideoTime = null;
  @SerializedName("expires")
  private Integer expires = null;
  @SerializedName("extraparam")
  private String extraparam = null;
  @SerializedName("has_shut_action")
  private Integer hasShutAction = null;
  @SerializedName("id")
  private String id = null;
  @SerializedName("image_style")
  private Integer imageStyle = null;
  @SerializedName("is_adx_sources")
  private Integer isAdxSources = null;
  @SerializedName("kuaishou_ad_info")
  private String kuaishouAdInfo = null;
  @SerializedName("next_encourage_coin_num")
  private Integer nextEncourageCoinNum = null;
  @SerializedName("ordinal")
  private Integer ordinal = null;
  @SerializedName("pangolin_popup_name")
  private String pangolinPopupName = null;
  @SerializedName("pic_max_size")
  private V1GetadPicMaxSize picMaxSize = null;
  @SerializedName("pic_size")
  private V1GetadPicMaxSize picSize = null;
  @SerializedName("planid")
  private String planid = null;
  @SerializedName("position")
  private String position = null;
  @SerializedName("request_time")
  private Integer requestTime = null;
  @SerializedName("scheme_uri")
  private String schemeUri = null;
  @SerializedName("sdk_mode")
  private Integer sdkMode = null;
  @SerializedName("sdk_source")
  private String sdkSource = null;
  @SerializedName("sdk_timeout")
  private BigDecimal sdkTimeout = null;
  @SerializedName("shake_type")
  private Integer shakeType = null;
  @SerializedName("show_ping")
  private List<String> showPing = null;
  @SerializedName("source")
  private String source = null;
  @SerializedName("source_type")
  private Integer sourceType = null;
  @SerializedName("tag_id")
  private Integer tagId = null;
  @SerializedName("tag_title")
  private String tagTitle = null;
  @SerializedName("tips_position")
  private Integer tipsPosition = null;
  @SerializedName("type")
  private Integer type = null;
  @SerializedName("user")
  private V1GetadUser user = null;
  @SerializedName("visible_percent")
  private Integer visiblePercent = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getAdSourceType() {
    return adSourceType;
  }
  public void setAdSourceType(Integer adSourceType) {
    this.adSourceType = adSourceType;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getAttrId() {
    return attrId;
  }
  public void setAttrId(Integer attrId) {
    this.attrId = attrId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAttrText() {
    return attrText;
  }
  public void setAttrText(String attrText) {
    this.attrText = attrText;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getClickPing() {
    return clickPing;
  }
  public void setClickPing(List<String> clickPing) {
    this.clickPing = clickPing;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getCloseByReason() {
    return closeByReason;
  }
  public void setCloseByReason(Integer closeByReason) {
    this.closeByReason = closeByReason;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public V1GetadDeepLinkTracking getDeepLinkTracking() {
    return deepLinkTracking;
  }
  public void setDeepLinkTracking(V1GetadDeepLinkTracking deepLinkTracking) {
    this.deepLinkTracking = deepLinkTracking;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getEncourageFinishTime() {
    return encourageFinishTime;
  }
  public void setEncourageFinishTime(Integer encourageFinishTime) {
    this.encourageFinishTime = encourageFinishTime;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getEncourageVideoTime() {
    return encourageVideoTime;
  }
  public void setEncourageVideoTime(Integer encourageVideoTime) {
    this.encourageVideoTime = encourageVideoTime;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getExpires() {
    return expires;
  }
  public void setExpires(Integer expires) {
    this.expires = expires;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getExtraparam() {
    return extraparam;
  }
  public void setExtraparam(String extraparam) {
    this.extraparam = extraparam;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getHasShutAction() {
    return hasShutAction;
  }
  public void setHasShutAction(Integer hasShutAction) {
    this.hasShutAction = hasShutAction;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getImageStyle() {
    return imageStyle;
  }
  public void setImageStyle(Integer imageStyle) {
    this.imageStyle = imageStyle;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getIsAdxSources() {
    return isAdxSources;
  }
  public void setIsAdxSources(Integer isAdxSources) {
    this.isAdxSources = isAdxSources;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getKuaishouAdInfo() {
    return kuaishouAdInfo;
  }
  public void setKuaishouAdInfo(String kuaishouAdInfo) {
    this.kuaishouAdInfo = kuaishouAdInfo;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getNextEncourageCoinNum() {
    return nextEncourageCoinNum;
  }
  public void setNextEncourageCoinNum(Integer nextEncourageCoinNum) {
    this.nextEncourageCoinNum = nextEncourageCoinNum;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getOrdinal() {
    return ordinal;
  }
  public void setOrdinal(Integer ordinal) {
    this.ordinal = ordinal;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPangolinPopupName() {
    return pangolinPopupName;
  }
  public void setPangolinPopupName(String pangolinPopupName) {
    this.pangolinPopupName = pangolinPopupName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public V1GetadPicMaxSize getPicMaxSize() {
    return picMaxSize;
  }
  public void setPicMaxSize(V1GetadPicMaxSize picMaxSize) {
    this.picMaxSize = picMaxSize;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public V1GetadPicMaxSize getPicSize() {
    return picSize;
  }
  public void setPicSize(V1GetadPicMaxSize picSize) {
    this.picSize = picSize;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPlanid() {
    return planid;
  }
  public void setPlanid(String planid) {
    this.planid = planid;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPosition() {
    return position;
  }
  public void setPosition(String position) {
    this.position = position;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getRequestTime() {
    return requestTime;
  }
  public void setRequestTime(Integer requestTime) {
    this.requestTime = requestTime;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSchemeUri() {
    return schemeUri;
  }
  public void setSchemeUri(String schemeUri) {
    this.schemeUri = schemeUri;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getSdkMode() {
    return sdkMode;
  }
  public void setSdkMode(Integer sdkMode) {
    this.sdkMode = sdkMode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSdkSource() {
    return sdkSource;
  }
  public void setSdkSource(String sdkSource) {
    this.sdkSource = sdkSource;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getSdkTimeout() {
    return sdkTimeout;
  }
  public void setSdkTimeout(BigDecimal sdkTimeout) {
    this.sdkTimeout = sdkTimeout;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getShakeType() {
    return shakeType;
  }
  public void setShakeType(Integer shakeType) {
    this.shakeType = shakeType;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getShowPing() {
    return showPing;
  }
  public void setShowPing(List<String> showPing) {
    this.showPing = showPing;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSource() {
    return source;
  }
  public void setSource(String source) {
    this.source = source;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getSourceType() {
    return sourceType;
  }
  public void setSourceType(Integer sourceType) {
    this.sourceType = sourceType;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getTagId() {
    return tagId;
  }
  public void setTagId(Integer tagId) {
    this.tagId = tagId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTagTitle() {
    return tagTitle;
  }
  public void setTagTitle(String tagTitle) {
    this.tagTitle = tagTitle;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getTipsPosition() {
    return tipsPosition;
  }
  public void setTipsPosition(Integer tipsPosition) {
    this.tipsPosition = tipsPosition;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getType() {
    return type;
  }
  public void setType(Integer type) {
    this.type = type;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public V1GetadUser getUser() {
    return user;
  }
  public void setUser(V1GetadUser user) {
    this.user = user;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getVisiblePercent() {
    return visiblePercent;
  }
  public void setVisiblePercent(Integer visiblePercent) {
    this.visiblePercent = visiblePercent;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2003 inlineResponse2003 = (InlineResponse2003) o;
    return (this.adSourceType == null ? inlineResponse2003.adSourceType == null : this.adSourceType.equals(inlineResponse2003.adSourceType)) &&
        (this.attrId == null ? inlineResponse2003.attrId == null : this.attrId.equals(inlineResponse2003.attrId)) &&
        (this.attrText == null ? inlineResponse2003.attrText == null : this.attrText.equals(inlineResponse2003.attrText)) &&
        (this.clickPing == null ? inlineResponse2003.clickPing == null : this.clickPing.equals(inlineResponse2003.clickPing)) &&
        (this.closeByReason == null ? inlineResponse2003.closeByReason == null : this.closeByReason.equals(inlineResponse2003.closeByReason)) &&
        (this.deepLinkTracking == null ? inlineResponse2003.deepLinkTracking == null : this.deepLinkTracking.equals(inlineResponse2003.deepLinkTracking)) &&
        (this.encourageFinishTime == null ? inlineResponse2003.encourageFinishTime == null : this.encourageFinishTime.equals(inlineResponse2003.encourageFinishTime)) &&
        (this.encourageVideoTime == null ? inlineResponse2003.encourageVideoTime == null : this.encourageVideoTime.equals(inlineResponse2003.encourageVideoTime)) &&
        (this.expires == null ? inlineResponse2003.expires == null : this.expires.equals(inlineResponse2003.expires)) &&
        (this.extraparam == null ? inlineResponse2003.extraparam == null : this.extraparam.equals(inlineResponse2003.extraparam)) &&
        (this.hasShutAction == null ? inlineResponse2003.hasShutAction == null : this.hasShutAction.equals(inlineResponse2003.hasShutAction)) &&
        (this.id == null ? inlineResponse2003.id == null : this.id.equals(inlineResponse2003.id)) &&
        (this.imageStyle == null ? inlineResponse2003.imageStyle == null : this.imageStyle.equals(inlineResponse2003.imageStyle)) &&
        (this.isAdxSources == null ? inlineResponse2003.isAdxSources == null : this.isAdxSources.equals(inlineResponse2003.isAdxSources)) &&
        (this.kuaishouAdInfo == null ? inlineResponse2003.kuaishouAdInfo == null : this.kuaishouAdInfo.equals(inlineResponse2003.kuaishouAdInfo)) &&
        (this.nextEncourageCoinNum == null ? inlineResponse2003.nextEncourageCoinNum == null : this.nextEncourageCoinNum.equals(inlineResponse2003.nextEncourageCoinNum)) &&
        (this.ordinal == null ? inlineResponse2003.ordinal == null : this.ordinal.equals(inlineResponse2003.ordinal)) &&
        (this.pangolinPopupName == null ? inlineResponse2003.pangolinPopupName == null : this.pangolinPopupName.equals(inlineResponse2003.pangolinPopupName)) &&
        (this.picMaxSize == null ? inlineResponse2003.picMaxSize == null : this.picMaxSize.equals(inlineResponse2003.picMaxSize)) &&
        (this.picSize == null ? inlineResponse2003.picSize == null : this.picSize.equals(inlineResponse2003.picSize)) &&
        (this.planid == null ? inlineResponse2003.planid == null : this.planid.equals(inlineResponse2003.planid)) &&
        (this.position == null ? inlineResponse2003.position == null : this.position.equals(inlineResponse2003.position)) &&
        (this.requestTime == null ? inlineResponse2003.requestTime == null : this.requestTime.equals(inlineResponse2003.requestTime)) &&
        (this.schemeUri == null ? inlineResponse2003.schemeUri == null : this.schemeUri.equals(inlineResponse2003.schemeUri)) &&
        (this.sdkMode == null ? inlineResponse2003.sdkMode == null : this.sdkMode.equals(inlineResponse2003.sdkMode)) &&
        (this.sdkSource == null ? inlineResponse2003.sdkSource == null : this.sdkSource.equals(inlineResponse2003.sdkSource)) &&
        (this.sdkTimeout == null ? inlineResponse2003.sdkTimeout == null : this.sdkTimeout.equals(inlineResponse2003.sdkTimeout)) &&
        (this.shakeType == null ? inlineResponse2003.shakeType == null : this.shakeType.equals(inlineResponse2003.shakeType)) &&
        (this.showPing == null ? inlineResponse2003.showPing == null : this.showPing.equals(inlineResponse2003.showPing)) &&
        (this.source == null ? inlineResponse2003.source == null : this.source.equals(inlineResponse2003.source)) &&
        (this.sourceType == null ? inlineResponse2003.sourceType == null : this.sourceType.equals(inlineResponse2003.sourceType)) &&
        (this.tagId == null ? inlineResponse2003.tagId == null : this.tagId.equals(inlineResponse2003.tagId)) &&
        (this.tagTitle == null ? inlineResponse2003.tagTitle == null : this.tagTitle.equals(inlineResponse2003.tagTitle)) &&
        (this.tipsPosition == null ? inlineResponse2003.tipsPosition == null : this.tipsPosition.equals(inlineResponse2003.tipsPosition)) &&
        (this.type == null ? inlineResponse2003.type == null : this.type.equals(inlineResponse2003.type)) &&
        (this.user == null ? inlineResponse2003.user == null : this.user.equals(inlineResponse2003.user)) &&
        (this.visiblePercent == null ? inlineResponse2003.visiblePercent == null : this.visiblePercent.equals(inlineResponse2003.visiblePercent));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.adSourceType == null ? 0: this.adSourceType.hashCode());
    result = 31 * result + (this.attrId == null ? 0: this.attrId.hashCode());
    result = 31 * result + (this.attrText == null ? 0: this.attrText.hashCode());
    result = 31 * result + (this.clickPing == null ? 0: this.clickPing.hashCode());
    result = 31 * result + (this.closeByReason == null ? 0: this.closeByReason.hashCode());
    result = 31 * result + (this.deepLinkTracking == null ? 0: this.deepLinkTracking.hashCode());
    result = 31 * result + (this.encourageFinishTime == null ? 0: this.encourageFinishTime.hashCode());
    result = 31 * result + (this.encourageVideoTime == null ? 0: this.encourageVideoTime.hashCode());
    result = 31 * result + (this.expires == null ? 0: this.expires.hashCode());
    result = 31 * result + (this.extraparam == null ? 0: this.extraparam.hashCode());
    result = 31 * result + (this.hasShutAction == null ? 0: this.hasShutAction.hashCode());
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.imageStyle == null ? 0: this.imageStyle.hashCode());
    result = 31 * result + (this.isAdxSources == null ? 0: this.isAdxSources.hashCode());
    result = 31 * result + (this.kuaishouAdInfo == null ? 0: this.kuaishouAdInfo.hashCode());
    result = 31 * result + (this.nextEncourageCoinNum == null ? 0: this.nextEncourageCoinNum.hashCode());
    result = 31 * result + (this.ordinal == null ? 0: this.ordinal.hashCode());
    result = 31 * result + (this.pangolinPopupName == null ? 0: this.pangolinPopupName.hashCode());
    result = 31 * result + (this.picMaxSize == null ? 0: this.picMaxSize.hashCode());
    result = 31 * result + (this.picSize == null ? 0: this.picSize.hashCode());
    result = 31 * result + (this.planid == null ? 0: this.planid.hashCode());
    result = 31 * result + (this.position == null ? 0: this.position.hashCode());
    result = 31 * result + (this.requestTime == null ? 0: this.requestTime.hashCode());
    result = 31 * result + (this.schemeUri == null ? 0: this.schemeUri.hashCode());
    result = 31 * result + (this.sdkMode == null ? 0: this.sdkMode.hashCode());
    result = 31 * result + (this.sdkSource == null ? 0: this.sdkSource.hashCode());
    result = 31 * result + (this.sdkTimeout == null ? 0: this.sdkTimeout.hashCode());
    result = 31 * result + (this.shakeType == null ? 0: this.shakeType.hashCode());
    result = 31 * result + (this.showPing == null ? 0: this.showPing.hashCode());
    result = 31 * result + (this.source == null ? 0: this.source.hashCode());
    result = 31 * result + (this.sourceType == null ? 0: this.sourceType.hashCode());
    result = 31 * result + (this.tagId == null ? 0: this.tagId.hashCode());
    result = 31 * result + (this.tagTitle == null ? 0: this.tagTitle.hashCode());
    result = 31 * result + (this.tipsPosition == null ? 0: this.tipsPosition.hashCode());
    result = 31 * result + (this.type == null ? 0: this.type.hashCode());
    result = 31 * result + (this.user == null ? 0: this.user.hashCode());
    result = 31 * result + (this.visiblePercent == null ? 0: this.visiblePercent.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2003 {\n");
    
    sb.append("  adSourceType: ").append(adSourceType).append("\n");
    sb.append("  attrId: ").append(attrId).append("\n");
    sb.append("  attrText: ").append(attrText).append("\n");
    sb.append("  clickPing: ").append(clickPing).append("\n");
    sb.append("  closeByReason: ").append(closeByReason).append("\n");
    sb.append("  deepLinkTracking: ").append(deepLinkTracking).append("\n");
    sb.append("  encourageFinishTime: ").append(encourageFinishTime).append("\n");
    sb.append("  encourageVideoTime: ").append(encourageVideoTime).append("\n");
    sb.append("  expires: ").append(expires).append("\n");
    sb.append("  extraparam: ").append(extraparam).append("\n");
    sb.append("  hasShutAction: ").append(hasShutAction).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  imageStyle: ").append(imageStyle).append("\n");
    sb.append("  isAdxSources: ").append(isAdxSources).append("\n");
    sb.append("  kuaishouAdInfo: ").append(kuaishouAdInfo).append("\n");
    sb.append("  nextEncourageCoinNum: ").append(nextEncourageCoinNum).append("\n");
    sb.append("  ordinal: ").append(ordinal).append("\n");
    sb.append("  pangolinPopupName: ").append(pangolinPopupName).append("\n");
    sb.append("  picMaxSize: ").append(picMaxSize).append("\n");
    sb.append("  picSize: ").append(picSize).append("\n");
    sb.append("  planid: ").append(planid).append("\n");
    sb.append("  position: ").append(position).append("\n");
    sb.append("  requestTime: ").append(requestTime).append("\n");
    sb.append("  schemeUri: ").append(schemeUri).append("\n");
    sb.append("  sdkMode: ").append(sdkMode).append("\n");
    sb.append("  sdkSource: ").append(sdkSource).append("\n");
    sb.append("  sdkTimeout: ").append(sdkTimeout).append("\n");
    sb.append("  shakeType: ").append(shakeType).append("\n");
    sb.append("  showPing: ").append(showPing).append("\n");
    sb.append("  source: ").append(source).append("\n");
    sb.append("  sourceType: ").append(sourceType).append("\n");
    sb.append("  tagId: ").append(tagId).append("\n");
    sb.append("  tagTitle: ").append(tagTitle).append("\n");
    sb.append("  tipsPosition: ").append(tipsPosition).append("\n");
    sb.append("  type: ").append(type).append("\n");
    sb.append("  user: ").append(user).append("\n");
    sb.append("  visiblePercent: ").append(visiblePercent).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
