/**
 * meetyou
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.electrolytej.main;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;

@ApiModel(description = "")
public class V1GetadDeepLinkTracking implements Serializable {
  
  @SerializedName("fallback_url")
  private List<String> fallbackUrl = null;
  @SerializedName("installed_invoke_fail_url")
  private List<String> installedInvokeFailUrl = null;
  @SerializedName("over_deep_link_url")
  private List<String> overDeepLinkUrl = null;
  @SerializedName("start_deep_link_url")
  private List<String> startDeepLinkUrl = null;
  @SerializedName("uninstall_invoke_fail_url")
  private List<String> uninstallInvokeFailUrl = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<String> getFallbackUrl() {
    return fallbackUrl;
  }
  public void setFallbackUrl(List<String> fallbackUrl) {
    this.fallbackUrl = fallbackUrl;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<String> getInstalledInvokeFailUrl() {
    return installedInvokeFailUrl;
  }
  public void setInstalledInvokeFailUrl(List<String> installedInvokeFailUrl) {
    this.installedInvokeFailUrl = installedInvokeFailUrl;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<String> getOverDeepLinkUrl() {
    return overDeepLinkUrl;
  }
  public void setOverDeepLinkUrl(List<String> overDeepLinkUrl) {
    this.overDeepLinkUrl = overDeepLinkUrl;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<String> getStartDeepLinkUrl() {
    return startDeepLinkUrl;
  }
  public void setStartDeepLinkUrl(List<String> startDeepLinkUrl) {
    this.startDeepLinkUrl = startDeepLinkUrl;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<String> getUninstallInvokeFailUrl() {
    return uninstallInvokeFailUrl;
  }
  public void setUninstallInvokeFailUrl(List<String> uninstallInvokeFailUrl) {
    this.uninstallInvokeFailUrl = uninstallInvokeFailUrl;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1GetadDeepLinkTracking v1GetadDeepLinkTracking = (V1GetadDeepLinkTracking) o;
    return (this.fallbackUrl == null ? v1GetadDeepLinkTracking.fallbackUrl == null : this.fallbackUrl.equals(v1GetadDeepLinkTracking.fallbackUrl)) &&
        (this.installedInvokeFailUrl == null ? v1GetadDeepLinkTracking.installedInvokeFailUrl == null : this.installedInvokeFailUrl.equals(v1GetadDeepLinkTracking.installedInvokeFailUrl)) &&
        (this.overDeepLinkUrl == null ? v1GetadDeepLinkTracking.overDeepLinkUrl == null : this.overDeepLinkUrl.equals(v1GetadDeepLinkTracking.overDeepLinkUrl)) &&
        (this.startDeepLinkUrl == null ? v1GetadDeepLinkTracking.startDeepLinkUrl == null : this.startDeepLinkUrl.equals(v1GetadDeepLinkTracking.startDeepLinkUrl)) &&
        (this.uninstallInvokeFailUrl == null ? v1GetadDeepLinkTracking.uninstallInvokeFailUrl == null : this.uninstallInvokeFailUrl.equals(v1GetadDeepLinkTracking.uninstallInvokeFailUrl));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.fallbackUrl == null ? 0: this.fallbackUrl.hashCode());
    result = 31 * result + (this.installedInvokeFailUrl == null ? 0: this.installedInvokeFailUrl.hashCode());
    result = 31 * result + (this.overDeepLinkUrl == null ? 0: this.overDeepLinkUrl.hashCode());
    result = 31 * result + (this.startDeepLinkUrl == null ? 0: this.startDeepLinkUrl.hashCode());
    result = 31 * result + (this.uninstallInvokeFailUrl == null ? 0: this.uninstallInvokeFailUrl.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1GetadDeepLinkTracking {\n");
    
    sb.append("  fallbackUrl: ").append(fallbackUrl).append("\n");
    sb.append("  installedInvokeFailUrl: ").append(installedInvokeFailUrl).append("\n");
    sb.append("  overDeepLinkUrl: ").append(overDeepLinkUrl).append("\n");
    sb.append("  startDeepLinkUrl: ").append(startDeepLinkUrl).append("\n");
    sb.append("  uninstallInvokeFailUrl: ").append(uninstallInvokeFailUrl).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
