/**
 * meetyou
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.electrolytej.main;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;

@ApiModel(description = "")
public class V1GetadPicMaxSize implements Serializable {
  
  @SerializedName("h")
  private Integer h = null;
  @SerializedName("w")
  private Integer w = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Integer getH() {
    return h;
  }
  public void setH(Integer h) {
    this.h = h;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Integer getW() {
    return w;
  }
  public void setW(Integer w) {
    this.w = w;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1GetadPicMaxSize v1GetadPicMaxSize = (V1GetadPicMaxSize) o;
    return (this.h == null ? v1GetadPicMaxSize.h == null : this.h.equals(v1GetadPicMaxSize.h)) &&
        (this.w == null ? v1GetadPicMaxSize.w == null : this.w.equals(v1GetadPicMaxSize.w));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.h == null ? 0: this.h.hashCode());
    result = 31 * result + (this.w == null ? 0: this.w.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1GetadPicMaxSize {\n");
    
    sb.append("  h: ").append(h).append("\n");
    sb.append("  w: ").append(w).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
