// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.electrolytej.network.model.SecondMsg in Profile.proto
import Wire

public struct SecondMsg {

    public var blah: Int32
    public var unknownFields: UnknownFields = .init()

    public init(blah: Int32) {
        self.blah = blah
    }

}

#if !WIRE_REMOVE_EQUATABLE
extension SecondMsg : Equatable {
}
#endif

#if !WIRE_REMOVE_HASHABLE
extension SecondMsg : Hashable {
}
#endif

extension SecondMsg : Sendable {
}

extension SecondMsg : ProtoMessage {

    public static func protoMessageTypeURL() -> String {
        return "type.googleapis.com/com.electrolytej.network.model.SecondMsg"
    }

}

extension SecondMsg : Proto3Codable {

    public init(from protoReader: ProtoReader) throws {
        var blah: Int32 = 0

        let token = try protoReader.beginMessage()
        while let tag = try protoReader.nextTag(token: token) {
            switch tag {
            case 1: blah = try protoReader.decode(Int32.self, encoding: .variable)
            default: try protoReader.readUnknownField(tag: tag)
            }
        }
        self.unknownFields = try protoReader.endMessage(token: token)

        self.blah = blah
    }

    public func encode(to protoWriter: ProtoWriter) throws {
        try protoWriter.encode(tag: 1, value: self.blah, encoding: .variable)
        try protoWriter.writeUnknownFields(unknownFields)
    }

}

#if !WIRE_REMOVE_CODABLE
extension SecondMsg : Codable {

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringLiteralCodingKeys.self)
        self.blah = try container.decode(Int32.self, forKey: "blah")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringLiteralCodingKeys.self)
        let includeDefaults = encoder.protoDefaultValuesEncodingStrategy == .include

        if includeDefaults || self.blah != 0 {
            try container.encode(self.blah, forKey: "blah")
        }
    }

}
#endif
