// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.electrolytej.network.model.SendCodeReq in SendCode.proto
import Wire

public struct SendCodeReq {

    public var unknownFields: UnknownFields = .init()

    public init() {
    }

}

#if !WIRE_REMOVE_EQUATABLE
extension SendCodeReq : Equatable {
}
#endif

#if !WIRE_REMOVE_HASHABLE
extension SendCodeReq : Hashable {
}
#endif

extension SendCodeReq : Sendable {
}

extension SendCodeReq : ProtoDefaultedValue {

    public static var defaultedValue: Self {
        .init()
    }
}

extension SendCodeReq : ProtoMessage {

    public static func protoMessageTypeURL() -> String {
        return "type.googleapis.com/com.electrolytej.network.model.SendCodeReq"
    }

}

extension SendCodeReq : Proto3Codable {

    public init(from protoReader: ProtoReader) throws {
        let token = try protoReader.beginMessage()
        while let tag = try protoReader.nextTag(token: token) {
            switch tag {
            default: try protoReader.readUnknownField(tag: tag)
            }
        }
        self.unknownFields = try protoReader.endMessage(token: token)

    }

    public func encode(to protoWriter: ProtoWriter) throws {
        try protoWriter.writeUnknownFields(unknownFields)
    }

}

#if !WIRE_REMOVE_CODABLE
extension SendCodeReq : Codable {

    public enum CodingKeys : CodingKey {
    }

}
#endif
