// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.electrolytej.network.model.TokenState in TokenState.proto
import Wire

/**
 * option java_outer_classname = "TokenState";
 */
public enum TokenState : Int32, CaseIterable, Proto3Enum, ProtoDefaultedValue {

    case NONE = 0
    case UNAUTHORIZED = 1
    case OTHERS = 2

    public static var defaultedValue: TokenState {
        TokenState.NONE
    }
    public var description: String {
        switch self {
        case .NONE: return "NONE"
        case .UNAUTHORIZED: return "UNAUTHORIZED"
        case .OTHERS: return "OTHERS"
        }
    }

}

extension TokenState : Sendable {
}
